### ISSUE TITLE
Illegal invocation

### ISSUE THREAD

**Issue by dudedigital** [mkay581/cookie-store#169]
I attempted to use `4.0.0-next.1` of this package with Vite and a Vue 3 component. After I added the import, I received the following error:

```
index.js:278 Uncaught TypeError: Illegal invocation
    at index.js:278:42
```
![image](https://user-images.githubusercontent.com/8594271/192029331-caae58bf-fc5e-430a-989c-c9a5316cb549.png)

I have another similar project where I used version `4.0.0-next.0` without issue. Any insight would be helpful.

**Comment by markcellus** [comment]
Hmm it may be something with how Vue/Vite is importing the component. I don't know much about Vue/Vite and how it works. Does it compile or just use the imports as native JS files in the browser? Can you shoot me a stackblitz or small repo that reproduces this? And I'll take a look and see what the issue may be.

**Comment by kulor** [comment]
I'm finding this error too in a React Webpack project. It's odd as it works fine in Safari but not Chrome. I created this test case that replicates the problem: https://stackblitz.com/edit/react-ts-grldcr?file=App.tsx
<img width="1306" alt="React_Ts__forked__-_StackBlitz_and_James_Broad_-_CTO" src="https://user-images.githubusercontent.com/38616/194776860-02599c7b-f124-4987-b807-9bcc704da89b.png">
